#  cloud:
#    gateway:
#      routes:
#        - id: payment-service-route
#          uri: lb://PAYMENT-SERVICE
#          predicates:
#            - Path=/payment/**, /payment-service/v3/api-docs
#          filters:
#            - RequestHashing=SHA-256
#
#        - id: order-service-route
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/order/**, /order-service/v3/api-docs
#          filters:
#            - RequestHashing=SHA-256