springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      #      this config is for api-gateway swagger-ui
      #      - url: /v3/api-docs
      #        name: API Gateway Service
      - url: /payment-service/v3/api-docs
        name: Payment Service
      - url: /order-service/v3/api-docs
        name: Order Service
      - url: /auth-service/v3/api-docs
        name: Auth Service
